-- -----------------------------------------------------
-- Table `mydb`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `donations`.`region` ;

CREATE TABLE IF NOT EXISTS `donations`.`region` (
  `ID_REGION` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `POPULATION` INT,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID_REGION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `donations`.`calendar` ;

CREATE TABLE IF NOT EXISTS `donations`.`calendar` (
  `ID_CALENDAR` INT NOT NULL AUTO_INCREMENT,
  `TYPE` VARCHAR(45) NOT NULL,
  `GCLOUD_ID` VARCHAR(255) NOT NULL,
  `ID_REGION` INT NOT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID_CALENDAR`),
  INDEX `fk_calendar_region_idx` (`ID_REGION` ASC),
  CONSTRAINT `fk_calendar_region`
    FOREIGN KEY (`ID_REGION`)
    REFERENCES `donations`.`region` (`ID_REGION`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `donations`.`institution` (
  `ID_INSTITUTION` INT NOT NULL AUTO_INCREMENT,
  `ADDRESS` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWD` VARCHAR(255) NOT NULL,
  `TYPES` VARCHAR(255),
  `SHELTER` TINYINT(1) DEFAULT 0,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_INSTITUTION`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `donations`.`event` (
  `ID_EVENT` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATE NOT NULL,
  `PERIOD` VARCHAR(45) NOT NULL,
  `GCLOUD_ID` VARCHAR(45) NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `ID_CALENDAR` INT NOT NULL,
  `ID_INSTITUTION` INT NOT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID_EVENT`),
  INDEX `fk_event_calendar1_idx` (`ID_CALENDAR` ASC),
  INDEX `fk_event_institution1_idx` (`ID_INSTITUTION` ASC),
  CONSTRAINT `fk_event_calendar1`
    FOREIGN KEY (`ID_CALENDAR`)
    REFERENCES `donations`.`calendar` (`ID_CALENDAR`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_event_institution1`
    FOREIGN KEY (`ID_INSTITUTION`)
    REFERENCES `donations`.`institution` (`ID_INSTITUTION`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;